\documentclass[UTF8]{ctexart}
%\documentclass[a4paper]{article}
% \usepackage[margin=1.25in]{geometry}
\usepackage[inner=2.0cm,outer=2.0cm,top=2.5cm,bottom=2.5cm]{geometry}
%\usepackage{CJK}
\usepackage{color}
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{bm}
\usepackage{hyperref}
\usepackage{multirow}
\usepackage{enumerate}
\usepackage{listings}
\usepackage{xcolor}
\usepackage{fontspec}
\setmainfont{Times New Roman}

\newcommand{\homework}[5]{
    \pagestyle{myheadings}
    \thispagestyle{plain}
    \newpage
    \setcounter{page}{1}
    \noindent
    \begin{center}
    \framebox{
        \vbox{\vspace{2mm}
        \hbox to 6.28in { {\bf 高级程序设计 \hfill #2} }
        \vspace{6mm}
        \hbox to 6.28in { {\Large \hfill \bf #1 \hfill} }
        \vspace{6mm}
        \hbox to 6.28in { {\it 指导老师： {\rm #3} \hfill 姓名： {\rm #4},学号： {\rm #5}}}
        \vspace{2mm}}
    }
    \end{center}
    % \markboth{#4 -- #1}{#4 -- #1}
    \vspace*{4mm}
}


\newcommand{\yahei}{\setCJKfamilyfont{yahei}{Microsoft YaHei} \CJKfamily{yahei}}




\newenvironment{solution}
{\color{blue} \paragraph{Solution.}}
{\newline \qed}

\begin{document}


%大标题在这里改！！！！！！！！！
\homework{实验报告}{2020 春}{陈家骏\phantom{ }黄书剑}{王晨渊}{181220057}

\lstset{numbers=left,numberstyle=\tiny,keywordstyle=\color{blue!70},commentstyle=\color{red!50!green!50!blue!50},frame=shadowbox, rulesepcolor=\color{red!20!green!20!blue!20},escapeinside=``,xleftmargin=2em,xrightmargin=2em, aboveskip=1em}

\section{概念题}
\subsection{请简述C++中异常处理的两种策略}
    就地处理：调用exit或abort
    异地处理：发现异常后在程序的其他地方进行处理。
\subsection{C++异常处理机制中try，throw和catch语句的作用分别是什么？}
    try启动异常处理机制。可以在throw异常对象之后，停止执行接下来的语句块。
    throw可以抛掷异常对象。
    catch捕获并处理异常对象
\subsection{请简述C++中断言（assertion）的概念和作用}
    断言是一个逻辑表达式，描述程序执行到断言处应满足的条件。
    用于发现、定位错误。

\section{编程题}
\subsection{ExceptionTest}
\begin{lstlisting}[language={[ANSI]C++}]
    #include <iostream>
    #include <cstdlib>
    #include <cmath>
    #include <fstream>
    #include <stdexcept>
    using namespace std;
    class ExceptionTest
    {
    private:
        int prime[100];    //存前100个素数（质数）
    public:
        //求分数，分子分母为a和b；分母为零异常
        double fraction(double a,double b);
        //求底数为10的对数，真数为a；真数为负异常
        double logarithm(double a);
        //求算出前100个素数，放在prime中，并写入文件；文件打开失败异常
        void calPrime(const char* address);
        //从prime中获取第i个素数；数组下标越界异常
        int getPrime(int i);
    };
    
    double ExceptionTest::fraction(double a, double b)
    {
        try
        {
            if(b==0) throw runtime_error("ZeroDivision!");
            return a/b;
        }
        catch(runtime_error err)
        {
            cerr <<err.what()<<endl;
            abort();
        }
    }
    
    double ExceptionTest::logarithm(double a)
    {
        try
        {
            if(a<=0) throw range_error("Negative log!");
            return log(a);
        }
        catch(range_error& e)
        {
            std::cerr << e.what() << '\n';
            abort();
        }
        
    }
    
    void ExceptionTest::calPrime(const char* address)
    {
        int prime_num=0;
        int cur_num = 2;
        while(prime_num!=100)
        {
            bool is_prime = true;
            for(int i=2;i<cur_num;i++)
            {
                if(cur_num%i==0)
                {
                    is_prime = false;
                    break;
                }
            }
            if(is_prime)
            {
                prime[prime_num]=cur_num;
                prime_num++;
            }
            cur_num++;
        }
        try
        {
            fstream file(address,ios::app|ios::in);
            if(file.fail()) throw runtime_error("Can't open file!");
            for(int i=0;i<100;i++)
            {
                file<<prime[i]<<",";
                if(i%10==9) file<<endl;
            }
            file.close();
        }
        catch(runtime_error& e)
        {
            cerr << e.what() << '\n';
            abort();
        }
    
    }
    
    int ExceptionTest::getPrime(int i)
    {
        try
        {
            if(!(0<=i&&i<=99)) throw invalid_argument("out of range!");
            return prime[i];
        }
        catch(invalid_argument& e)
        {
            cerr << e.what() << '\n';
            abort();
        }
    }
    
    int main()
    {
        ExceptionTest a;
        a.fraction(1,0);
        a.calPrime("primes.txt");
    }
\end{lstlisting}
\subsection{注册}
\begin{lstlisting}[language={[ANSI]C++}]
    #include <string>
    #include <iostream>
    #include <fstream>
    using namespace std;
    class Web
    {
    public:
        void inputName();
        void inputAge();
        void inputPhone();
        void uploadFile();
        void enroll();
    private:
        string name;
        int age;
        string phone;
        string address;
    };
    
    void Web::enroll()
    {
        inputName();
        inputAge();
        L1:
        try
        {
            inputPhone();
        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
            goto L1;
        }
        L2:
        try
        {
            uploadFile();
        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
            goto L2;
        }   
        
    }
    
    void Web::inputName()
    {
        cout<<"Input your name.End with ENTER"<<endl;
        getline(cin,name);
    }
    
    void Web::inputAge()
    {
        cout<<"Input your Age.End with ENTER"<<endl;
        string age_buf;
        getline(cin,age_buf);
        age = stoi(age_buf);
        if(age<11 || age>18)
        {
            cerr<<"Inappropriate age!"<<endl;
            abort();
        }
    }
    
    void Web::inputPhone()
    {
        cout<<"Input your Phone Number.End with ENTER"<<endl;
        getline(cin,phone);
        for(char s:phone)
        {
            if(!((s>='0'&&s<='9')||s=='-')) 
                throw runtime_error("Inappropriate phone!");
        } 
    }
    
     void Web::uploadFile()
     {
        cout<<"Input your Article Address.End with ENTER"<<endl;
        getline(cin,address);
        fstream file(address,ios::in);
        if(file.fail()) throw runtime_error("Something wrong with your address!");
        //pretends to have some operation
        //as no format is given, I can't do anything.
        file.close();
     }
    
    int main()
    {
        Web myweb;
        myweb.enroll();
    }
\end{lstlisting}
\subsection{memcpy}

\begin{lstlisting}[language={[ANSI]C++}]
    #include <iostream>
    using namespace std;
    void *memcpy(void *dst, void *src, unsigned count);
    int main()
    {
        int arr[]={1,2,3,4,5,6,7,8,9,10};
        
        for(int i=0;i<10;i++)
        {
            cout<<arr[i]<<",";
        }
        cout<<endl;
        try
        {
    //        memcpy(NULL,arr+3,4);
    //        memcpy(arr+4,NULL,4);
            memcpy(arr+3,arr+4,16);
        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        for(int i=0;i<10;i++)
        {
            cout<<arr[i]<<",";
        }
    
    }
    
    void *memcpy(void *dst, void *src, unsigned count)
    {
    
        if(!dst || !src) throw runtime_error("NULL pointer!");
        if(!((char*)dst>=(char*)src+count||(char*)dst+count<=(char*)src))
        {
            throw out_of_range("Intersected!");
        }
        for(unsigned i=0;i<count;i++)
        {
            *((char*)dst+i)=*((char*)src+i);
        }
        return dst;
\end{lstlisting}


\subsection{书上的小问题}

\begin{lstlisting}[language={[ANSI]C++}]
    #include <iostream>
    using namespace std;
    int main()
    {
        int n,*p;//p173
        cin>>n;
        L1:
        try
        {
            p = new int[n];
            if(!p) throw runtime_error("Malloc Failed!");
        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
            goto L1;
        }
        delete[] p;
        L2:
        try
        {
            max(NULL,10);
        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }
    
    int max(int x[],int num)//p131
    {
        int max_index =0;
        if(!x) throw runtime_error("NULL point!");
        for(int i=1;i<num;i++)
        {
            if(x[i]>x[max_index]) max_index = i;
        }
        return max_index;
    }
    
\end{lstlisting}


\end{document}
